class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.SpeedCommand = 'speedtest'
        self.StatsCommand = 'stats'#10
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.ShellCommand = 'sl'
        self.IgPostCommand = 'posts'
        self.IgTvCommand = 'igtv'
        self.IgFollowersCommand= 'followers'
        self.IgFollowingCommand= 'following'
        self.IgFansCommand= 'fans'
        self.IgNotFollowingCommand = 'notfollowing'
        self.IgFeedCommand = 'feed'#10
        self.IgSavedCommand = 'saved'
        self.IgTaggedCommand = 'tagged'
        self.IgStoryCommand = 'story'
        self.IgStoriesCommand = 'stories'
        self.IgHighlightsCommand = 'highlights'
        self.LoginCommand = 'login'
        self.IgLogoutCommand = 'logout'
        self.IgAccountCommand = 'account'
        self.IgSearchCommand = 'ig'
        self.IgMirrorCommand='mirror'#10
BotCommands = _BotCommands()
